#pragma once

#include "NativeGameplayTags.h"

namespace AbyssGameplayTags
{
	ABYSS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	ABYSS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	ABYSS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	ABYSS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	ABYSS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ABYSS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	ABYSS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	ABYSS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	ABYSS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);
}
